In [5]:
from localbot_localization.src.dataset import LocalBotDataset
import torch

In [2]:
train_dataset = LocalBotDataset(seq=110, npoints=1000)

In [10]:
for i in range(80):
    print(i)
    print(sum(torch.isnan(train_dataset[i][0])))

0
tensor([0, 0, 0])
1
tensor([2, 2, 2])
2
tensor([0, 0, 0])
3
tensor([0, 0, 0])
4
tensor([0, 0, 0])
5
tensor([0, 0, 0])
6
tensor([1, 1, 1])
7
tensor([0, 0, 0])
8
tensor([0, 0, 0])
9
tensor([0, 0, 0])
10
tensor([0, 0, 0])
11
tensor([0, 0, 0])
12
tensor([0, 0, 0])
13
tensor([0, 0, 0])
14
tensor([0, 0, 0])
15
tensor([0, 0, 0])
16
tensor([0, 0, 0])
17
tensor([0, 0, 0])
18
tensor([0, 0, 0])
19
tensor([0, 0, 0])
20
tensor([0, 0, 0])
21
tensor([286, 286, 286])
22
tensor([0, 0, 0])
23
tensor([165, 165, 165])
24
tensor([14, 14, 14])
25
tensor([0, 0, 0])
26
tensor([78, 78, 78])
27
tensor([1, 1, 1])
28
tensor([0, 0, 0])
29
tensor([0, 0, 0])
30
tensor([0, 0, 0])
31
tensor([0, 0, 0])
32
tensor([0, 0, 0])
33
tensor([0, 0, 0])
34
tensor([0, 0, 0])
35
tensor([0, 0, 0])
36
tensor([0, 0, 0])
37
tensor([0, 0, 0])
38
tensor([0, 0, 0])
39
tensor([0, 0, 0])
40
tensor([0, 0, 0])
41
tensor([1, 1, 1])
42
tensor([0, 0, 0])
43
tensor([251, 251, 251])
44
tensor([0, 0, 0])
45
tensor([0, 0, 0])
46
tensor([0, 0, 0])

In [3]:
train_dataset[0][0].shape

torch.Size([1000, 3])